module.exports = {
    main: [
        {
            id: 'introduction',
            type: 'doc',
        },
        {
            items: [
                'getting-started/installation',
                'getting-started/usage',
                'getting-started/default-theme',
            ],
            label: 'Getting started',
            type: 'category',
        },
        {
            items: [
                'components/ActionButton',
                'components/AdjustableContainer',
                'components/Button',
                'components/Caption',
                'components/Card',
                'components/CenterContainer',
                'components/Checkbox',
                'components/Collapsible',
                'components/Divider',
                'components/ExtendedCard',
                'components/FlexContainer',
                'components/Heading',
                'components/Icon',
                'components/Label',
                'components/LinearGradient',
                'components/Link',
                'components/Padding',
                'components/PasswordInput',
                'components/Rating',
                'components/RowContainer',
                'components/Scalable',
                'components/ScreenContainer',
                'components/Shadow',
                'components/Spacer',
                'components/Subheading',
                'components/Text',
                'components/TextInput',
            ],
            label: 'Components',
            type: 'category',
        },
        {
            id: 'faq',
            type: 'doc',
        },
    ],
};
